# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20170502_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.Collection_Category'),
        ),
    ]
