# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_collection_variable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection_variable',
            name='variable_value',
            field=models.CharField(max_length=500),
        ),
    ]
