# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailupdate', '0002_auto_20170417_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email_address',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
