# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=30)),
                ('source_creation_date', models.DateTimeField(verbose_name=b'source creation date')),
            ],
        ),
    ]
