# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='source_url',
            field=models.CharField(default='addurl', max_length=200),
            preserve_default=False,
        ),
    ]
