# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0002_source_source_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='source_creation_date',
            new_name='date_create',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='source_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='source_url',
            new_name='url',
        ),
        migrations.AddField(
            model_name='source',
            name='key',
            field=models.CharField(default='blank', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='oauth_version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='source',
            name='rss_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='source',
            name='secret',
            field=models.CharField(default='blank', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='url_call',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
