# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0004_auto_20170309_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='dict0_flag',
            field=models.BooleanField(default=False),
        ),
    ]
