# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 01:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0008_source_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='category',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='source_user',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='source.Source'),
        ),
        migrations.AlterField(
            model_name='source_user',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
