# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0009_auto_20170425_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='organization',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
    ]
